[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-identity = "0.8.0"
actix-session = "0.10.1"
actix-web = "4.9.0"
chrono = "0.4.39"
rand = "0.9.0"
serde = "1.0.218"
serde_json = "1.0.139"
sqlx = "0.8.3"
tokio = "1.43.0"
uuid = "1.14.0"
